name: HugoBuildAndDeploy

on:
  workflow_dispatch: # To have the ability to run the workflow manually

  push:
    branches: [main]

env:
  NAME: ./
  CONTAINER-NAME: home-page

jobs:
  ReleaseProd:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ secrets.PAT_TOKEN }}

      # Install Hugo
      - run: sudo snap install hugo

      # Build the hugo repository
      - run: hugo -e development --baseURL "https://dev.lna-dev.net"
        working-directory: ./${{ env.NAME }}/

      # Download Secure-File
      - name: base64-to-file
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: "config"
          encodedString: ${{ secrets.KUBECTL_CONFIG }}

      # Deploy Kubernetes YAML
      - name: Deploy script
        run: |
          chmod +x ./.github/workflows/deploy.sh
          ./.github/workflows/deploy.sh         